language: python

matrix:
  include:
    - python: 2.7
      env: PYTEST_FLAGS="--flake8 --isort" PY_VER=_2.7
    - python: 3.5
      env: PYTEST_FLAGS="--flake8 --isort --mypy"
    - python: 3.6
      env: PYTEST_FLAGS="--flake8 --isort --mypy"
    - python: 3.7
      env: PYTEST_FLAGS="--flake8 --isort --mypy"
      dist: xenial
      sudo: true

install:
  - pip install --upgrade pip pip-tools
  - pip-sync requirements${PY_VER}.txt dev-requirements${PY_VER}.txt
  - pip install -e .

script:
  - py.test $PYTEST_FLAGS tests/ figcan/
