language: python

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install --upgrade pip pipenv
  - pipenv install --dev --system

script:
  - py.test --flake8 --mypy --isort tests/ figcan/
